export const T = {
  GET_TODOLISTS: 'GET_TODOLIST',
  GET_LABELS: 'GET_LABELS',
  GET_TODO: 'GET_TODO',
  ADD_TODO: 'ADD_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  PURGE_TODO: 'PURGE_TODO'
}
