export const T = {
  GET_TASKS: 'GET_TASKLIST',
  GET_TASK: 'GET_TASK',
  ADD_TASK: 'ADD_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  DELETE_TASK: 'DELETE_TASK',
  MOVE_TASK: 'MOVE_TASK',
  PURGE_TASKS: 'PURGE_TASKS'
}
