Resources:
  TodoTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: group
          AttributeType: S
        - AttributeName: groupId
          AttributeType: S
        - AttributeName: ownerId
          AttributeType: S
      KeySchema:
        - AttributeName: group
          KeyType: HASH
        - AttributeName: groupId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
      - IndexName: group-ownerId-index
        KeySchema:
          - AttributeName: group
            KeyType: HASH
          - AttributeName: ownerId
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      TableName: ${self:custom.todoTable}
