Resources:
  GroupTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        -
          AttributeName: groupId
          AttributeType: S
        -
          AttributeName: group
          AttributeType: S
        -
          AttributeName: ownerId
          AttributeType: S
      KeySchema:
        -
          AttributeName: groupId
          KeyType: HASH
        -
          AttributeName: group
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
      - IndexName: group-ownerId-index
        KeySchema:
          -
            AttributeName: ownerId
            KeyType: HASH
          -
            AttributeName: group
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      TableName: todo-group-${self:provider.stage}

  UserTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      AttributeDefinitions:
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: createdAt
          AttributeType: N
      KeySchema:
        -
          AttributeName: id
          KeyType: HASH
        -
          AttributeName: createdAt
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: todo-user-${self:provider.stage}
